# Generated by Django 4.2.3 on 2023-09-15 13:25

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentimentmodel',
            name='query_end_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='sentimentmodel',
            name='query_start_date',
            field=models.DateField(default=datetime.date(2022, 9, 15)),
        ),
    ]
