# Generated by Django 4.2.3 on 2023-09-21 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_sentimentmodel_query_end_date_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SentimentModel',
        ),
    ]
