# Generated by Django 4.2.5 on 2023-09-29 16:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ML', '0002_alter_sentimentmodel_query_start_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Query_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_name', models.CharField(max_length=255, unique=True)),
                ('comments', models.TextField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='sentimentmodel',
            name='query_start_date',
            field=models.DateField(default=datetime.date(2022, 9, 29)),
        ),
    ]
